### PR TITLE
JUnit5 migration

### PR DESCRIPTION
**Pull request by brbog**
@rzo1 : a summary of the pull request so it's easier for you to review.

Regarding the build:
- I noticed that the Spock tests weren't executed during the build.
- The Groovy/Spock parts inside the Maven build script are not yet removed, that would be for a later commit (they are already no longer used).
- surefire is upgraded to a milestone M7, because you mentioned M6 and I'm using M7 successfully in my other projects.

Regarding the tests:
- The Spock tests contained code that was not up to date with the latest API of various classes.
- At the moment all tests are migrated to JUnit5 and they get compiled and executed during the build, so that's an improvement :-).
- Formatting will be off here and there, because the work was literally renaming .groovy files to .java and fixing coding problems using copy pastes while having non-compiling code (confuses the formatter).
- I'm using AssertJ which is a continuation of fest-assert which was already way more useful (and readable) than JUnit's own Hamcrest library.
- There are still 6 failing tests -> I would need an extra pair of eyes for those, it might help that you know more of the history of the project. I'll make a follow-up post with more explanation.
- There is 1 test disabled ("ignored"). This is because of coding that changed after updating to the latest HttpClient version and the test can no longer be made to fail in the same way.

Regarding the code:
- Based on the tests I learned that the exception handling inside WebCrawler could receive a partially filled in Page object. More specifically, when a timeout occurs it is possible that the Page object not only contains the webURL, but also the status code and response headers (so timeout occurs while transferring the page payload). This means that the new methods that replace the deprecated ones get an "upgrade" in the argument list, so they no longer receive WebURL and Exception, but rather Page and Exception (with a comment that the Page object will only be partially populated). This should be trivial to see and fix when upgrading after following the (removed) deprecated method upgrade guidelines of version 4.10.1.

All in all this pull request should already be a nice improvement, even when there are 6 tests failing (see follow-up post).

### CODE REVIEW

**Comment by brbog** [comment]
@rzo1 : about the failing tests.

### BasicAuthTest
Not sure what changed to make this test fail. The code never allowed anything more than provide credentials, but using HttpClient manually, I would use following code to define that I want authentication to be done preemptively:
```java
		final BasicScheme basicAuth = new BasicScheme();
		basicAuth.initPreemptive(new UsernamePasswordCredentials(userName, password));
```
So now I'm wondering how this used to work. This might require code changes unless you know of a use case where this (still) works. I expect the test to work the same as when it was written in Spock syntax (WireMock does the real magic in both the Spock and JUnit tests).

### PublicSuffixTest
This detects the wrong "registered domain" and "subdomain". This code has never been touched, even in the previous repository, so I'm probably looking over something. It seems like `AbstractWebURL.setURL(...)` is not eagerly trying to detect the registered domain. It goes from right to left, and whenever a candidate satisfies following test:
```java
if (tldList.isRegisteredDomain(candidate)) {
    rd = candidate;
}
```
... searching for a bigger possible registered domain name stops, and everything else is put as subdomain.

### TLDListOnlineTest
I think this will be identical to the previous problem.

**Comment by brbog** [comment]
Implementation for issue https://github.com/rzo1/crawler4j/issues/113

**Comment by rzo1** [comment]
It looks like the Groovy tests were never executed (at least for a long time) as the code only differs in the use of a `StringBuilder` and a missing `InternetDomainName.isValid(domain)` from `guava`, which we could add back by shading Guava and strip away the unnecessary garbage ;) Side note: This will not change anything, i.e. test will still fail.

Basically, I am wondering, if the test values are correct, i.e. are we sure we are testing the right things here?

It looks like the code assumes, that `com` is the domain and `www.example` is the sub domain.  But I guess, that the original intention of `domain` here is the **registered domain**. I think, that this "bug" / change in behaviour was introduced by switching to crawler commons instead of using Guava''s `InternetDomainName`.

I will push a fix to this PR.

**Comment by rzo1** [comment]
Regarding `BasicAuthTest`, I guess it was just broke or broken earlier by moving to HTTP Client 5. Don't think, that this should be a blocker for this PR, so maybe we can just `@Disable` it and check for the BasicAuth part later.

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
I noticed, that the tests take a siginifcant amount of time (even locally). I guess, that we need to do anotheri iteration in order to speed things up ;)

**Comment by brbog** [comment]
> It looks like the Groovy tests were never executed (at least for a long time) as the code only differs in the use of a `StringBuilder` and a missing `InternetDomainName.isValid(domain)` from `guava`, which we could add back by shading Guava and strip away the unnecessary garbage ;) Side note: This will not change anything, i.e. test will still fail.
> 
> It looks like the code assumes, that `com` is the domain and `www.example` is the sub domain. But I guess, that the original intention of `domain` here is the **registered domain**. I think, that this "bug" / change in behaviour was introduced by switching to crawler commons instead of using Guava''s `InternetDomainName`.

I'm not even sure crawler commons is the issue. Maybe the code in crawler4j should start testing with the biggest possible String first and start removing parts from the left. That way the largest possible registered domain returns true and everything else is subdomain.

**Comment by brbog** [comment]
> I noticed, that the tests take a siginifcant amount of time (even locally). I guess, that we need to do anotheri iteration in order to speed things up ;)

The WireMock based tests are indeed a lot slower. It's possible this was always the case, but even then it's nice to have a possibility for a quick build and one with slow tests enabled (typically integration tests).

**Comment by rzo1** [comment]
> I'm not even sure crawler commons is the issue.

The problem originated from my misunderstanding of how the (undocumented) code should behave while doing the crawler-commons migration. I spend some time yesterday to debug and adjust accordingly to past the tests. The basic idea here is, that `getDomain` should return the private / registerable / pay-level domain while everything in front of it is the subdomain. This definition if things is okaish while working on a crawler but imho has some definition gaps ;)

Nevertheless, it now behaves as before (without doing a Guava shade in crawler4j).

> The WireMock based tests are indeed a lot slower. It's possible this was always the case, but even then it's nice to have a possibility for a quick build and one with slow tests enabled (typically integration tests).

Yes. Perhaps we should make them real IT tests using failsafe + a profile, so we can run them in CI (only).

**Pull request merged**
