### PR TITLE
bug: a detected url: "http://<html></html>"

### PR DESCRIPTION
**Pull request by brbog**
AllowSingleLevelDomain true together with IncludeBinaryContentInCrawling true causes an issue because of a detected url: `"http://<html></html>"`

More explanation + workaround is in the Javadoc of the tests.

I added JUnit5 dependencies because the "crawler4j-commons"-subproject was still virgin regarding testing. Maybe a good moment to decide whether continuing with Spock is useful or if it's time to gradually let go of him/it?

### CODE REVIEW

**Comment by rzo1** [comment]
Hi! Thanks for the PR - I will look into it as soon as my ISP provides me with Internet again ;-)

**Comment by brbog** [comment]
See also issue https://github.com/rzo1/crawler4j/issues/74

**Comment by rzo1** [comment]
> Maybe a good moment to decide whether continuing with Spock is useful or if it's time to gradually let go of him/it?

I don't speak spock, so I am +1 for dropping it ;)

**Comment by brbog** [comment]
> > Maybe a good moment to decide whether continuing with Spock is useful or if it's time to gradually let go of him/it?
> 
> I don't speak spock, so I am +1 for dropping it ;)

I enjoyed the framework a lot and I actually can speak (and don't particularly like) Spock... I might regret this, but since there are not that many tests and all I need to get used to is WireMock (which is on my todo-list anyway), I'm volunteering to try to get rid of as much as possible of these tests -> read: translate to JUnit5 tests.

In my personal opinion I think Groovy was mostly a mistake for the Java community, and moving away from Spock after you moved away from Gradle is probably an evolution that you support? I have my "own ways" of course, but in the critical points I think we're not far apart, so just met me know if you feel like it would help :-).

**Pull request merged**
