### PR TITLE
Groovy expulsion

### PR DESCRIPTION
**Pull request by brbog**

### CODE REVIEW

**Comment by brbog** [comment]
I guess we can now say we have crawler4j-ng (**n**o **G**roovy) :-).

**Comment by rzo1** [comment]
Success ;)

**Comment by brbog** [comment]
@rzo1 : I need to work on some other priorities now and the code seems to be in a good state, so I wouldn't mind a first v5 release. wdyt?

**Comment by rzo1** [comment]
let's do it.

**Comment by brbog** [comment]
Contributes to issue https://github.com/rzo1/crawler4j/issues/113

**Comment by rzo1** [comment]
@brbog Sonatype is done. Should be available soon

**Pull request merged**
